name: user_repository
description: a dart package that manages the user domain
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'


dependencies:
  uuid: ^3.0.7
  equatable: ^2.0.5