name: login_bloc
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  user_repository:
    path: packages/user_repository
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  formz: ^0.6.0
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
